### ISSUE TITLE
Add <ZH-CN> localization to the zkBob app.

### ISSUE THREAD

**Issue by Yondcutie** [zkBob/docs#16]
[zkbob chineses translation.json](https://github.com/zkBob/docs/files/13041590/zkbob.chineses.translation.json)

Adding Simplified Chinese translation here for zkBob

**Comment by 0xdeval** [comment]
Thank you for your interest in the development of zkBob. We'd be happy to review your translations and add ZK-CH localization to the app. You can track the progress of this issue

**Comment by 0xdeval** [comment]
The ZK-CN localization was added
https://forum.zkbob.com/t/two-new-localizations-for-zkbob-submitted-by-our-community/51
