### ISSUE TITLE
zkBob_usecaseexamples

### ISSUE THREAD

**Issue by ulyanas** [zkBob/docs#6]
For zkBob wondering about creating a few other graphics related to use cases. We have this private transfer use case and will also create a salary one. Is it enough info to create a flow diagram?

https://docs.zkbob.com/zkbob-overview/basic-concepts/use-case-example

Could create several diagrams as well - one for each action or combine a few? Not sure what would look best.

Example of other zkBob illustrations:
https://docs.zkbob.com/implementation/contracts-and-circuits
https://docs.zkbob.com/implementation/transaction-overview/transaction-types
https://docs.zkbob.com/implementation/transaction-overview/the-transaction-lifecycle

**Assign to Outcrowd**

**Comment by tgladilina** [comment]
Create 2 illustration for
https://docs.zkbob.com/zkbob-overview/basic-concepts/use-case-examples

Assign to outcrowd. Paid

**Comment by tgladilina** [comment]
![Image](https://user-images.githubusercontent.com/103045386/197700000-aa487cd0-752f-4a90-91af-5b9b1979adb8.png)

Feedback 

Mojmir Racak
Seems clear to me. Although if I wouldn't be familiar  with the project, I would probably struggle to understand what exactly is happening with Carl and Dave = maybe we can make it even more clear that these transactions are zk wallet <-> zk wallet, within the zkBob and not Web3 wallet <-> Web3 wallet

Andrew Gross
Agree - maybe highlighting the boxes as “public” and “private” could help.
Also the withdrawal is to a newly generated EOA, which is not tied to the original EOA used for the deposit. Should make that more clear.

**Comment by tgladilina** [comment]
@andogro  images have been updated. Please check 

![Image](https://user-images.githubusercontent.com/103045386/199588226-f6d5c910-27be-4123-aed9-214bac7092e1.png)

![Image](https://user-images.githubusercontent.com/103045386/199588227-d5df0130-a5fb-427c-8904-d164fef4899f.png)

**Comment by tgladilina** [comment]
@andogro Final mockups attached

[Scheme_usercases.zip](https://github.com/zkBob/docs/files/9954551/Scheme_usercases.zip)
